"""Phase 4: Posting.

Formats the final review and posts it to GitHub via the MCP post_review_comment tool.
"""
from __future__ import annotations

from datetime import datetime

import structlog

from ...mcp.tools import post_review_comment
from ...models import EvalScore, PhaseTrace
from ...telemetry.spans import agent_span

logger = structlog.get_logger(__name__)


def _format_review_body(
    review_text: str,
    eval_scores: list[EvalScore],
    avg_score: float,
    iterations: int,
) -> str:
    """Append a quality scorecard footer to the review body."""
    score_rows = "\n".join(
        f"| {s.dimension.replace('_', ' ').title()} | {'⭐' * round(s.score)} {s.score:.1f} | {s.notes} |"
        for s in eval_scores
    )

    footer = f"""

---
<details>
<summary>🔍 DevMind Quality Scorecard (avg: {avg_score:.2f}/5.0 · {iterations} iteration{'s' if iterations > 1 else ''})</summary>

| Dimension | Score | Notes |
|---|---|---|
{score_rows}

*Generated by [DevMind](https://github.com/Arbiter09/DevMind) — autonomous PR review agent*
</details>"""

    return review_text + footer


async def run_posting(
    review_text: str,
    eval_scores: list[EvalScore],
    avg_score: float,
    iterations: int,
    pr_number: int,
    repo: str,
) -> PhaseTrace:
    """Post the formatted review to GitHub and return a phase trace."""
    started = datetime.utcnow()

    formatted = _format_review_body(review_text, eval_scores, avg_score, iterations)

    with agent_span("devmind.posting", {"pr.number": pr_number, "pr.repo": repo}):
        result = await post_review_comment(
            pr_number=pr_number, repo=repo, body=formatted
        )
        logger.info("posting.complete", pr_number=pr_number, review_id=result.get("review_id"))

    return PhaseTrace(
        phase="posting",
        started_at=started,
        ended_at=datetime.utcnow(),
        details={"review_id": result.get("review_id"), "state": result.get("state")},
    )
